import os
from flask import Flask, render_template, jsonify, request
import json
# Optional pandas import – if unavailable, use dummy data
try:
    import pandas as pd
except ImportError:
    pd = None

# Paths
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(BASE_DIR, "data")
MODEL_DIR = os.path.join(BASE_DIR, "models")
REPORTS_DIR = os.path.join(BASE_DIR, "reports")
SHAP_DIR = os.path.join(MODEL_DIR, "shap_plots")

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/summary')
def summary():
    # Load model metrics from a JSON file generated by reports/generate.py (placeholder)
    summary_path = os.path.join(REPORTS_DIR, 'summary.json')
    if os.path.exists(summary_path):
        with open(summary_path) as f:
            data = json.load(f)
    else:
        data = {
            "model_auc": None,
            "sharpe": None,
            "total_return": None,
            "win_rate": None,
        }
    return jsonify(data)

@app.route('/api/predictions')
def predictions():
    # Load latest predictions CSV (placeholder)
    pred_path = os.path.join(DATA_DIR, 'predictions.csv')
    if os.path.exists(pred_path):
        df = pd.read_csv(pred_path)
        records = df.to_dict(orient='records')
    else:
        records = []
    return jsonify(records)

@app.route('/api/backtest')
def backtest():
    equity_path = os.path.join(REPORTS_DIR, 'equity_curve.csv')
    if os.path.exists(equity_path):
        df = pd.read_csv(equity_path, parse_dates=['date'])
        records = df.to_dict(orient='records')
    else:
        records = []
    return jsonify(records)

@app.route('/api/shap')
def shap():
    # Return paths to SHAP plot images
    summary_img = os.path.join('static', 'shap', 'shap_summary.png')
    waterfall_img = os.path.join('static', 'shap', 'shap_waterfall_0.png')
    return jsonify({"summary": summary_img, "waterfall": waterfall_img})

@app.route('/api/predict', methods=['POST'])
def predict():
    data = request.get_json()
    ticker = data.get('ticker')
    # Placeholder logic – real implementation loads model and predicts
    result = {
        "ticker": ticker,
        "probability": 0.0,
        "prediction": "unknown"
    }
    return jsonify(result)

if __name__ == '__main__':
    # Serve static assets from the web/static folder
    app.run(host='0.0.0.0', port=5000, debug=True)
